#!/usr/bin/env bash
# Development stack guidance (doc 17 R4). Does not auto-start long-lived processes.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
echo "Smart Material System — dev stack startup guide"
echo ""
echo "1) Start API (loopback :8010):"
echo "   ./scripts/start_api.sh"
echo ""
echo "2) Start frontend dev server:"
echo "   cd frontend && npm run dev"
echo "   # Vite default: http://127.0.0.1:5173 (proxies /api to :8010)"
echo ""
echo "3) Optional models (requires weights under /models):"
echo "   ./scripts/models.sh status"
echo "   ./scripts/models.sh start big|fast|embed|all"
echo "   # legacy wrappers (deprecated): start_vllm_big.sh / start_fast_7b.sh / start_vllm_embed.sh / start_vllm_big27.sh"
echo ""
echo "4) Build SPA for single-entry (:8010 serves frontend/dist):"
echo "   cd frontend && npm run build"
echo ""
echo "5) Runtime acceptance:"
echo "   PYTHONPATH=. python3 scripts/check_runtime.py"
echo ""
echo "Design targets: fast :8000, big :8001, embed :8002 (see app/config.py)."
echo "Current acceptance: use check_runtime.py output (runtime_level / blocking)."
